# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_post_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='default title', max_length=100),
            preserve_default=False,
        ),
    ]
