# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_post_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[web.models.validate_email], verbose_name='Your Email'),
        ),
    ]
