# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170328_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
